---
- name: DB 삭제 작업
  hosts: databases
  gather_facts: yes
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_config_url: http://192.168.10.10
    db_config_src_path_small: "{{ db_config_url }}/my.cnf.small"
    db_config_src_path_large: "{{ db_config_url }}/my.cnf.large"
    db_config_path: /etc/my.cnf
    db_service: mariadb
  tasks:
    - name: stop_db
      service:
        name: "{{ db_service }}"
        state: stopped

    - name: delete_db
      yum:
        name: "{{ db_service }}"
        state: absent