---
- name: 환경 파일 배포
  gather_facts: yes
  hosts: all
  tasks:
    - name: 환경 파일 배포 - $HOME/.bashrc
      template: 
        src: templates/bashrc.j2
        dest: /home/devops/.bashrc
        owner: devops
        group: devops
        mode: '0644'